version: "3.9"

services:
  app:
    build: .
    container_name: backend
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${RAM}
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrator
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DBNAME: ${MYSQL_DBNAME}
      QUEUE_SIZE: ${QUEUE_SIZE}
      CPUS: ${CPUS}
      RAM: ${RAM}
    volumes:
      - ./:/app
    restart: always
  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  migrator:
    image: migrate/migrate
    container_name: migrator
    command: ["-source=file:///migrations", "-database=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DBNAME}", "up"]
    depends_on:
      - db
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DBNAME: ${MYSQL_DBNAME}
    volumes:
      - ./migrations:/migrations
    restart: on-failure:10
