version: "3.9"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend_scheduler
    ports:
      - "8090:8090"
    depends_on:
      - db_scheduler
      - migrator_scheduler
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DBNAME: ${MYSQL_DBNAME}
      QUEUE_SIZE: ${QUEUE_SIZE}
      CPUS: ${CPUS}
      RAM: ${RAM}
    volumes:
      - ./:/app
    restart: always
  db_scheduler:
    image: mysql:8.0 #39dj29dl2d9l2/ven-db_scheduler:1.0
    container_name: db_scheduler
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  migrator_scheduler:
    image: migrate/migrate
    container_name: migrator_scheduler
    command: ["-source=file:///migrations", "-database=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DBNAME}", "up"]
    depends_on:
      - db_scheduler
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DBNAME: ${MYSQL_DBNAME}
    volumes:
      - ./migrations:/migrations
    restart: on-failure:10
