// Code generated by MockGen. DO NOT EDIT.
// Source: scheduler-node/internal/scheduler (interfaces: Scheduler)

// Package scheduler_mock is a generated GoMock package.
package scheduler_mock

import (
	context "context"
	reflect "reflect"
	store "scheduler-node/internal/store"

	gomock "github.com/golang/mock/gomock"
)

// MockScheduler is a mock of Scheduler interface.
type MockScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulerMockRecorder
}

// MockSchedulerMockRecorder is the mock recorder for MockScheduler.
type MockSchedulerMockRecorder struct {
	mock *MockScheduler
}

// NewMockScheduler creates a new mock instance.
func NewMockScheduler(ctrl *gomock.Controller) *MockScheduler {
	mock := &MockScheduler{ctrl: ctrl}
	mock.recorder = &MockSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduler) EXPECT() *MockSchedulerMockRecorder {
	return m.recorder
}

// SubmitWorkflow mocks base method.
func (m *MockScheduler) SubmitWorkflow(arg0 context.Context, arg1 store.VENInfo, arg2 store.WorkflowInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitWorkflow", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitWorkflow indicates an expected call of SubmitWorkflow.
func (mr *MockSchedulerMockRecorder) SubmitWorkflow(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitWorkflow", reflect.TypeOf((*MockScheduler)(nil).SubmitWorkflow), arg0, arg1, arg2)
}
